### ISSUE TITLE
Extend the example with futures

### ISSUE THREAD

**Issue by mikela** [sematext/kamon-spm-example#1]
Hello Sematext! 
I'm trying to include [Automatic TraceContext Propagation with Futures](http://kamon.io/documentation/kamon-scala/0.6.6/overview/) but this transaction doesn't show up in my dashboard (for example under "Monitoring > Trasanctions > Throughput/Latency"). 
Could you please extend your example with Futures?
Thank you!

**Comment by qkoshelev** [comment]
Hello!
I've added the example for Future and withNewContext. You should add 'autoFinish = true' to see trace under "Monitoring > Trasanctions > Throughput/Latency".  Please note: To see your trace under Transactions > Traces you should add delay >30ms.
